apiVersion: apps/v1
kind: Deployment
metadata:
  name: spendwise-fo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spendwise-fo
  template:
    metadata:
      labels:
        app: spendwise-fo
    spec:
      containers:
        - name: spendwise-fo
          image: prasantdas123/spendwise-app:jun01-v2
          ports:
            - containerPort: 80
          env:
            - name: VITE_AUTH0_DOMAIN
              value: "dev-c5ls7veng3ljfc5g.us.auth0.com"
            - name: VITE_AUTH0_AUDIENCE
              value: "https://spendwise-backend-api"
            - name: VITE_AUTH0_FO_CLIENT_ID
              value: "uqUxxBkX0zTbqMdcZNeFJnf72Ds6YI0L"
            - name: VITE_AUTH0_CLIENT_ID
              value: "uqUxxBkX0zTbqMdcZNeFJnf72Ds6YI0L"
            - name: VITE_AUTH0_CLIENT_SECRET
              value: "kB98Ev4O7ST1PsRU1TGdVMFcXDFXdrAnA-wYcy3LPHUCsrPa70FCAoq-r0TlUton"
            - name: VITE_STRIPE_PUBLIC_KEY
              value: "pk_test_51Td5fpB6qil4AjdcWVSP6PkA3EIgOCqcdNbwMufdsqYGN5x47A4nyV7g0mvRPzxbUZcBo6tsT43ypNmNNg9ScqND00KbkZLjU4"
            - name: VITE_LOCAL_API_URL
              value: "http://172.168.76.236:8080"