apiVersion: v1
kind: Pod
metadata:
  name: web-server-pod
  labels:
    app: nginx
    tier: frontend
    environment: development
spec:
  containers:
  - name: nginx-container
    image: nginx
#Labels added: app=nginx, tier=frontend, environment=development