apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: nginx
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
#Selector: Matches Pods with app=nginx and tier=frontend.
#This ensures the Service routes traffic only to Pods labeled as frontend Nginx servers.