apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: env
            operator: In
            values:
            - prasant          
  containers:
  - name: nginx
    image: nginx:latest
    
